### PR TITLE
[RELOCATE] MimeType & FailedAttempt functions

### PR DESCRIPTION
**Pull request by xerc**

### CODE REVIEW

**Comment by xerc** [comment]
https://wiki.php.net/rfc/calls_in_constant_expressions

**Comment by xerc** [comment]
may someone wants to join/comment about these changes incl. AVIF inclusion (after MERGE) or should it be wasted time?

**Comment by wazum** [comment]
Sorry, but how I structure my code is up to me (and I won't change that for no obvious reason).
If you find a bug, please submit a pull request, otherwise use the time for something more valuable. Thank you!

**Comment by xerc** [comment]
kk - clean code seems undesirable

**Pull request closed without merging**
